version: "2"

services:
  tracd:
    image: solsson/trac:engine

    restart: unless-stopped
    volumes:
      - ../trac-env/:/trac
    ports:
      - 81:80
    links:
      - mysql
    depends_on:
      - mysql
    command: ["-s", "/trac", "--auth", "*,/trac/conf/digest_passwd,pjtadmin"]

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - 443:443
      - 80:80
      - 22:22
    container_name: gitlab

    restart: unless-stopped
    volumes:
      - /Users/beweiche/gitlab/config:/etc/gitlab
      - /Users/beweiche/gitlab/logs:/var/log/gitlab
      - /Users/beweiche/gitlab/data:/var/opt/gitlab

  trac-hub:
    image: bwl21/trac-hub
    build: .

    restart: unless-stopped

    volumes:
      - ..:/usr/src/myapp
      - /Users/beweiche/gitlab/data:/var/opt/gitlab
    links:
      - mysql
    depends_on:
      - mysql

    working_dir: /usr/src/myapp/trac-hub
    entrypoint: ./trac-hub
    command: -h




volumes:
  mysql: {

  }
  www: {}
  log: {}
