#!/usr/bin/env ruby

require 'json'
require 'logger'
require 'octokit'
require 'optparse'
require 'sequel'
require 'yaml'

class Migrator
  def initialize(trac, github, users, labels, deduplicate)
    @trac = trac
    repo = github['repo']
    logins = github['logins']
    first = logins.shift
    @clients = Hash.new(GitHub.new(first[0], first[1], repo))
    @default = @clients[nil]
    logins.each { |user, pass| @clients[user] = GitHub.new(user, pass, repo) }
    @users = Hash[users]
    @collaborators = @default.collaborators.map { |c| c[:login] }
    @labels = Hash[labels.map { |cat, rx| [cat, rx.map { |f, t| [Regexp.new(f), t] }] }]
    @milestones = Hash[@default.list_milestones.map { |m| [m[:title], m[:number]] }]
    if deduplicate
      @issues = Hash[@default.list_issues.map { |i| [i[:title], i] }]
    end
    @ticket_to_issue = {}
  end

  def migrate(start_ticket = 0)
    migrate_milestones
    migrate_tickets(start_ticket)
  end

  private

  def migrate_milestones
    $logger.info('migrating milestones')
    @trac.milestones.each do |milestone|
      name = milestone[:name]
      if @milestones.has_key?(name)
        $logger.warn("skipping already existing milestone '#{name}'")
        next
      end
      opts = {}
      opts[:state] = milestone[:completed] == 0 ? 'open' : 'closed'
      opts[:description] = milestone[:description]
      begin
        t = DateTime.parse(milestone[:due])
        opts[:due_on] = t.to_time
      rescue
        $logger.warn("ignoring milestone date '#{milestone[:due]}'")
      end
      $logger.info("creating new milestone #{name}")
      ms = @default.create_milestone(name, opts)
      @milestones[name] = ms[:number]
    end
  end


  # Creates github issues for trac tickets.
  def migrate_tickets(start_ticket)
    $logger.info('migrating issues')
    # We match the issue title to determine whether an issue exists already.
    total_tickets = @trac.tickets.count
    @trac.tickets.order(:id).where{id >= start_ticket}.all.each do |ticket|
      # FIXME: needs porting to multi-user scenario.
      #total_tickets -= 1
      #rate_check(100) if total_tickets % 100 == 0
      title = ticket[:summary]
      if @issues and @issues.has_key?(title)
        $logger.warn("skipping existing issue '#{title}'")
        next
      end
      begin
        issue = @clients[@users[ticket[:reporter]]].create_issue(title, '')
        @issues[title] = issue if @issues
        $logger.info("created issue ##{issue[:number]} for ticket #{ticket[:id]}")
        [:description, :owner, :milestone, :type,
         :component, :priority, :version, :resolution].map do |cat|
          issue = change_issue(issue, ticket[:reporter], cat.to_s, ticket[cat])
        end
        $logger.debug('replaying ticket history')
        @trac.changes.where(:ticket => ticket[:id]).each do |chg|
          issue = change_issue(issue, chg[:author], chg[:field], chg[:newvalue])
        end
        $logger.info("migrated ticket #{ticket[:id]}")
      rescue Interrupt
        $logger.error("cancelled migration of ticket #{ticket[:id]} '#{title}'")
        exit 1
      end
    end
  end

  # Replays the ticket history of a given ticket and returns the new issue.
  def change_issue(issue, author, category, value)
    i = issue[:number]
    client = @clients[@users[author]]
    case category
    when 'milestone'
      ms = @milestones[value]
      return issue unless ms
      $logger.debug("issue #{i}: updating milestone to '#{ms}'")
      return client.update_issue_opts(issue, :milestone => ms)
    when 'owner'
      owner = @users[value]
      return issue unless (owner and @collaborators.include?(owner))
      $logger.debug("issue #{i}: updating assignee to '#{owner}'")
      return client.update_issue_opts(issue, :assignee => owner)
    when 'status'
      case value
      when 'closed'
        $logger.debug("issue #{i}: closing")
        return client.close_issue(i)
      when 'reopened'
        $logger.debug("issue #{i}: reopening")
        return client.reopen_issue(i)
      end
    when 'summary'
      $logger.debug("issue #{i}: updating title to '#{value}'")
      return client.update_issue(i, value, issue[:body])
    when 'description'
      $logger.debug("issue #{i}: updating body")
      body = markdownify(author, value)
      return client.update_issue(i, issue[:title], body)
    when /resolution|priority|component|type|version/
      old_labs = issue[:labels].map { |l| l[:name] }
      return issue unless @labels.has_key?(category)
      t, f = @labels[category].partition { |pat, rep| pat.match(value) }
      if t.empty?
        $logger.warn("issue #{i}: no match for label '#{value}' in '#{category}'")
        return issue
      elsif t.size > 1
        $logger.error("issue #{i}: more than one match for '#{value}' in '#{category}'")
        exit 1
      end
      new_labs = old_labs.reject { |lab| f.find { |pat, rep| pat.match(lab) } }
      if old_labs.size != new_labs.size
        $logger.debug("issue #{i}: removed existing labels in '#{category}'")
      end
      new_label = t[0][1]
      return issue if new_label.empty?
      $logger.debug("issue #{i}: adding label '#{new_label}'")
      new_labs << new_label
      $logger.debug("issue #{i}: updating lables to #{new_labs}")
      return client.update_issue_opts(issue, :labels => new_labs)
    when 'comment'
      return issue if value.empty? || value =~ /Milestone.*deleted/
      max_len = 30
      excerpt = value[0, max_len].gsub(/\n|\r/, ' ')
      excerpt << '...' if value.size > max_len
      $logger.debug("issue #{i}: adding comment '#{excerpt}'")
      client.add_comment(i, markdownify(author, value))
    when /keywords|cc|reporter/ # TODO
    end
    return issue
  end

  def rate_check(client, bound, seconds=30)
    limit, remaining = client.rate_limit
    $logger.debug("#{remaining}/#{limit} operations available")
    while remaining < bound
      $logger.info("less than #{bound} operations viable, sleeping...")
      sleep(seconds)
    end
  end

  def markdownify(author, str)
    # Line endings
    str.gsub!("\r\n", "\n")
    # Code
    str.gsub!(/\{\{\{([^\n]+?)\}\}\}/, '`\1`')
    str.gsub!(/\{\{\{(.+?)\}\}\}/m, '```\1```')
    # Headings
    str.gsub!(/\=\=\=\=\s(.+?)\s\=\=\=\=/, '#### \1')
    str.gsub!(/\=\=\=\s(.+?)\s\=\=\=/, '### \1')
    str.gsub!(/\=\=\s(.+?)\s\=\=/, '## \1')
    str.gsub!(/\=\s(.+?)\s\=[\s\n]*/, '# \1')
    # Links
    str.gsub!(/\[(http[^\s\[\]]+)\s([^\[\]]+)\]/, '[\2](\1)')
    str.gsub!(/\!(([A-Z][a-z0-9]+){2,})/, '\1')
    # Font styles
    str.gsub!(/'''(.+?)'''/, '**\1**')
    str.gsub!(/''(.+?)''/, '*\1*')
    # Lists
    str.gsub!(/(^\s+)\*/, '\1-')
    str.gsub!(/(^\s+)(\d)\./, '\1\2.')
    # Authorship
    user = @users[author]
    if not @clients.has_key?(user)
      reporter = user ? "[#{user}](https://github.com/#{user})" : author
      str.insert(0, "**Original reporter**: *#{reporter}*\n\n")
    end
    str
  end
end

class Trac
  attr_reader :milestones, :tickets, :changes
  def initialize(db)
    $logger.info('loading milestones and tickets')
    @db = db
    @milestones = @db[:milestone]
    @tickets = @db[:ticket]
    @changes = @db[:ticket_change]
  end
end

class GitHub
  def initialize(user, pass, repo)
    @user = user
    $logger.debug("#{@user} connects to github repo '#{repo}'")
    @client = Octokit::Client.new(:login => @user, :password => pass)
    @repo = repo
  end

  def collaborators
    @client.collaborators(@repo)
  end

  def list_milestones
    open = @client.list_milestones(@repo, :state => 'open')
    closed = @client.list_milestones(@repo, :state => 'closed')
    open + closed
  end

  def create_milestone(*args)
    @client.create_milestone(@repo, *args)
  end

  def list_issues
    $logger.debug("#{@user} fetches all open issues in #{@repo}")
    open = fetch_pagewise { |i| @client.list_issues(@repo, :page => i) }
    closed = fetch_pagewise do |i|
      @client.list_issues(@repo, {:state => 'closed', :page => i})
    end
    open + closed
  end

  def create_issue(*args)
    $logger.debug("#{@user} creates issue '#{args[0]}'")
    if args[1].size > 2**16
      msg = "\n\n*(issue truncated due to size)*"
      $logger.warn("truncating issue '#{args[0]}' (#{args[1].size} bytes)")
      args[1] = args[1][0, 65300] + msg
    end
    @client.create_issue(@repo, *args)
  end

  def update_issue(*args)
    @client.update_issue(@repo, *args)
  end

  def close_issue(*args)
    @client.close_issue(@repo, *args)
  end

  def reopen_issue(*args)
    @client.reopen_issue(@repo, *args)
  end

  def add_comment(*args)
    @client.add_comment(@repo, *args)
  end

  def update_issue_opts(issue, opts)
    update_issue(issue[:number], issue[:title], issue[:body], opts)
  end

  def rate_limit
    [@client.rate_limit, @client.rate_limit_remaining]
  end

  private

  def fetch_pagewise
    result = []
    begin
      i = 1;
      loop do
        $logger.debug("fetching page #{i}")
        page = yield i
        break if page.empty?
        result += page
        i += 1
      end
    end
    $logger.debug("fetched #{result.size} elements")
    result
  end
end

class Options < Hash
  def initialize(argv)
    super()
    opts = OptionParser.new do |opts|
      opts.banner = "#{$0}, available options:"
      opts.on('-c config', '--config', 'set the configuration file') do |c|
        self[:config] = c
      end
      opts.on('-d', '--deduplicate',
              'do not migrate tickets w/ duplicate titles') do |d|
        self[:deduplicate] = d
      end
      opts.on_tail('-h', '--help', 'display this help and exit') do |help|
        puts(opts)
        exit
      end
      opts.on('-s', '--start-at ID', 'be verbose') do |id|
        self[:start] = id
      end
      opts.on('-v', '--verbose', 'be verbose') do |v|
        self[:verbose] = v
      end
      begin
        opts.parse!(argv)
        if not self[:config]
          default = File.join(File.dirname(__FILE__), 'config.yaml')
          raise 'missing configuration file' unless File.exists?(default)
          self[:config] = default
        end
        self[:start] = 0 unless self[:start]
      rescue => e
        STDERR.puts(e)
        STDERR.puts('run with -h to see available options')
        exit 1
      end
    end
  end
end

if __FILE__ == $0
  opts = Options.new(ARGV)
  cfg = YAML.load_file(opts[:config])

  # Setup logger.
  $logger = Logger.new(STDERR)
  $logger.level = opts[:verbose] ? Logger::DEBUG : Logger::INFO
  $logger.formatter = proc do |severity, datetime, progname, msg|
    time = datetime.strftime('%Y-%m-%d %H:%M:%S')
    "[#{time}] #{severity}#{' ' * (5 - severity.size + 1)}| #{msg}\n"
  end

  # Setup database.
  db = nil
  if sqlite = cfg['trac']['sqlite']
    file = sqlite['file']
    if not File.exists?(file)
      $logger.error("no such file: #{file}")
      exit 1
    end
    $logger.debug("connecting to SQLite databse '#{file}'")
    db = Sequel.sqlite(file)
  end
  if not db
    $logger.error('could not connect to trac databse')
    exit 1
  end

  trac = Trac.new(db)
  migrator = Migrator.new(trac, cfg['github'], cfg['users'], cfg['labels'],
                          opts[:deduplicate])
  migrator.migrate(opts[:start])
end
